# Generated by Django 6.0.2 on 2026-03-11 13:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('submission_type', models.CharField(choices=[('BRANCH_DROPOFF', 'Branch Drop-Off'), ('PICKUP', 'Pickup Request')], default='BRANCH_DROPOFF', max_length=20)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_address', models.TextField()),
                ('receiver_city', models.CharField(max_length=100)),
                ('receiver_postal_code', models.CharField(max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pickup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('RECEIVED', 'Received'), ('LOADED', 'Loaded'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], default='REGISTERED', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parcels', to='drivers.driverprofile')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='vehicles.vehicle')),
                ('current_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_parcels', to='branches.branch')),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_parcels', to='branches.branch')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_parcels', to='branches.branch')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_parcels', to='customers.customerprofile')),
            ],
            options={
                'db_table': 'parcels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_image', models.ImageField(upload_to='delivery_proofs/')),
                ('delivery_notes', models.TextField(blank=True)),
                ('signature_required', models.BooleanField(default=False)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_proofs', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proofs', to='parcels.parcel')),
            ],
            options={
                'db_table': 'delivery_proofs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='parcel_images/')),
                ('image_type', models.CharField(choices=[('receipt', 'Receipt Confirmation'), ('packaging', 'Packaging'), ('loading', 'Loading Confirmation'), ('damage', 'Damage Evidence'), ('delivery', 'Delivery Proof'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parcels.parcel')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_parcel_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcel_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelTrackingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('RECEIVED', 'Received'), ('LOADED', 'Loaded'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_histories', to='branches.branch')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='parcels.parcel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcel_tracking_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelTransitUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('transit_status', models.CharField(choices=[('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('reached_destination', 'Reached Destination')], max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_updates', to='drivers.driverprofile')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_updates', to='parcels.parcel')),
            ],
            options={
                'db_table': 'parcel_transit_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_address', models.TextField()),
                ('parcel_description', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SCHEDULED', 'Scheduled'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('preferred_pickup_date', models.DateField()),
                ('preferred_pickup_time', models.TimeField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to='drivers.driverprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='customers.customerprofile')),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_pickups', to='branches.branch')),
                ('estimated_parcel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_request', to='parcels.parcel')),
            ],
            options={
                'db_table': 'pickup_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['tracking_number'], name='parcels_trackin_6efce7_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='parcels_status_ed18a4_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['sender'], name='parcels_sender__5be588_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['created_at'], name='parcels_created_e01331_idx'),
        ),
    ]
