# Generated by Django 6.0.2 on 2026-03-11 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PARCEL_STATUS_CHANGE', 'Parcel Status Change'), ('IMAGE_UPLOAD', 'Image Upload'), ('QR_SCAN', 'QR Code Scan'), ('TRANSIT_UPDATE', 'Transit Update'), ('PICKUP_REQUEST', 'Pickup Request'), ('DELIVERY_CONFIRMATION', 'Delivery Confirmation'), ('REPORT_GENERATED', 'Report Generated')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=500, null=True)),
                ('object_display', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_logs_user_id_6193b2_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs_action_bcaa71_idx'), models.Index(fields=['model_name', '-created_at'], name='audit_logs_model_n_47bca0_idx')],
            },
        ),
    ]
